#pragma once

enum class STAT_TYPE
{
	STAT_TYPE_FLOAT,
	STAT_TYPE_INT,
	STAT_TYPE_BOOL,
	STAT_TYPE_CELL, // <- 기본적으로 Float이나 일정 간격으로 나누어 사용하는 스탯, EX) 특수 공격용 게이지 
	STAT_TYPE_END
};

enum class STAT_NORMAL
{
	STAT_POINT_BODY,
	STAT_POINT_STAMINA,
	STAT_POINT_WEIGHT,
	STAT_POINT_POWER,
	STAT_POINT_SKILL,
	STAT_POINT_EVOLUTION,
	STAT_GAUGE_HP,
	STAT_GAUGE_STAMINA,
	STAT_GAUGE_REGION,
	STAT_GAUGE_WEIGHT,
	STAT_GADRIGAIN,
	STAT_END
};

enum class STAT_DEF
{
	STAT_DEF_PHYSICS,
	STAT_DEF_FIRE,
	STAT_DEF_ELECTLIC,
	STAT_DEF_ACID,
	STAT_DEF_COLLAPSE,
	STAT_DEF_COLLISION,
	STAT_DEF_BROKEN,
	STAT_DEF_SWORD,
	STAT_DEF_HIT,
	STAT_DEF_PIRCE,
	STAT_END
};

enum class BUFF_INDEX
{
	BUFF_FIRE,
	BUFF_ELECTRIC,
	BUFF_AICD,
	BUFF_CONTAMINATION,
	BUFF_COLLAPSE,
	BUFF_HIT,
	BUFF_BROKEN,
	BUFF_END
};